### ISSUE TITLE
Error - dataloader - TypeError: "cannot create weak reference to 'builtin_function_or_method' object"

### ISSUE THREAD

**Issue by sophiabano** [tynguyen/unsupervisedDeepHomographyRAL2018#8]
I have been trying to run the homography_CNN_synthetic.py. I have followed to the instructions and managed to generate the synthesis data. But when I run homography_CNN_synthetic.py in test mode, I get the following error in dataloader.py", line 156, in __init__
    full_I = self.read_image(I_path, [self.full_img_h, self.full_img_w], channels=3)

TypeError: cannot create weak reference to 'builtin_function_or_method' object

(complete error pasted below)

I tried debugging it and no luck. Any idea what might be the cause of this error?

python homography_CNN_synthetic.py --mode test --lr 5e-4 --loss_type h_loss 
<==================== Loading data ===================>

===> There are totally 5000 test files
===> Test: There are totally 5000 Test files
Traceback (most recent call last):
  File "homography_CNN_synthetic.py", line 622, in <module>
    test_homography()
  File "homography_CNN_synthetic.py", line 608, in test_homography
    test_obj = TestHomography()
  File "homography_CNN_synthetic.py", line 429, in __init__
    data_loader = Dataloader(test_dataloader_params, shuffle=True) # No shuffle
  File "/home/sophiabano/Python_code/unsupervisedDeepHomographyRAL2018/code/dataloader.py", line 156, in __init__
    full_I = self.read_image(I_path, [self.full_img_h, self.full_img_w], channels=3)
  File "/home/sophiabano/Python_code/unsupervisedDeepHomographyRAL2018/code/dataloader.py", line 240, in read_image
    path_length = string_length_tf(image_path)[0]
  File "/home/sophiabano/Python_code/unsupervisedDeepHomographyRAL2018/code/dataloader.py", line 44, in string_length_tf
    return tf.py_func(len, [t], [tf.int64])
  File "/home/sophiabano/Environments/projectunsupervisedhomo/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 384, in py_func
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/home/sophiabano/Environments/projectunsupervisedhomo/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 199, in _internal_py_func
    token = _py_funcs.insert(func)
  File "/home/sophiabano/Environments/projectunsupervisedhomo/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 100, in insert
    self._funcs[token] = func
  File "/usr/lib/python2.7/weakref.py", line 108, in __setitem__
    self.data[key] = KeyedRef(value, self._remove, key)
  File "/usr/lib/python2.7/weakref.py", line 278, in __new__
    self = ref.__new__(type, ob, callback)
TypeError: cannot create weak reference to 'builtin_function_or_method' object

**Comment by shangrongyang** [comment]
Hi, I had meet the same question.  Did you find the way to solve this problem?

**Comment by dek8v5** [comment]
I solved it by lowering the version of tensorflow to tensorflow==1.2.1

**Comment by liyandongpy** [comment]
Hi, I had meet the same question. Did you find the way to solve this problem?
